### ISSUE TITLE
How to show mappings, `msg.sender`, etc

### ISSUE THREAD

**Issue by rstormsf** [trufflesuite/truffle-debugger#29]
I'd like to see in debug mode values of mappings, native vars(msg.sender) and call `view/constant` functions
How do I do it?

**Comment by gnidan** [comment]
Hi @rstormsf, thanks for finding all the things we don't support yet :)

Adding support for native variables in the coming weeks, that should be pretty straightforward.

Re: `view` functions, I assume you're asking to [execute arbitrary Solidity](https://github.com/trufflesuite/truffle-debugger/issues/14)? This is non-trivial, although we have some ideas on how to implement and hope to add soon.

**Comment by gnidan** [comment]
Closing this ticket in favor of #32 #30, etc.
