### ISSUE TITLE
Watch Expressions Always 'undefined'

### ISSUE THREAD

**Issue by fredfortier** [trufflesuite/truffle-debugger#46]
I'm debugging from `truffle develop` with Truffle v4.1.3.

I ran a unit test which completed successfully. From the result, I can confirm that the business logic ran correctly. I'm trying to debug to look at the value of variables during execution. I'm using the `+:var` command to watch specific variables. 

While I can step through my code, it just seems to execute linearly line-by-line. The variable which I'm watching are always undefined:
```
118:             bytes32[] memory args = new bytes32[](deal.encryptedDestAddresses.length + 1);
119:             args[0] = bytes32(dealId);
120:             for (uint i = 0; i < deal.encryptedDestAddresses.length; i++) {
                                  ^

:dealId
  undefined
```

**Comment by gnidan** [comment]
Are all variables undefined? If you type `v`, what do you see?

**Comment by gnidan** [comment]
@fredfortier can you try upgrading to Truffle v4.1.4 and see if this problem still persists?

**Comment by gnidan** [comment]
Assuming this issue has been resolved. Closing for issue maintenance. Let me know if you run into further problems and I'll reopen. Thanks!
