### ISSUE TITLE
truffle debug failed

### ISSUE THREAD

**Issue by yinhaoscu** [trufflesuite/truffle-debugger#52]
Truffle version 4.1.4
I follow the tutorial debugging-a-smart-contract. In truffle(develop)> debug Transaction ID, I got the followings,
Compiling .\contracts\Migrations.sol...
Compiling .\contracts\Store.sol...

Gathering transaction data...

redux-saga error: uncaught at session.saga
at session.saga
 TypeError: Cannot read property 'binary' of undefined

How to fix it. Thanks.

**Comment by gnidan** [comment]
This is a known issue. Closing this as duplicate of #51 

Thanks!
