### ISSUE TITLE
Underflow issues yield unexpected output

### ISSUE THREAD

**Issue by bmmpxf** [trufflesuite/truffle-debugger#66]
In a Solidity file that populates an array with values some of which are negative:

0, 1, 1, 0, -1, -1 ...

When the array is of type `uint[]`, there is an underflow error, but weirder, the array seems to add more elements (twice as many) which might be the debugger misreading the output.

When the array is of type `uint8[]` there is still an underflow error, but no extra elements are shown by the debugger.

For example:

```
15:     // set entry equal to sum of two previous entries
16:     for (uint i=2; i < n ; i++) {
17:       fibseries.push(fibseries[i-1] - fibseries[i-2]);
          ^^^^^^^^^

debug(development:0x539e8bde...)> v

          i: 9
          n: 10
  fibseries: [ 0, 0, 0, 0, 0, 0, 0, 0, 0 ]

debug(development:0x539e8bde...)> o

Fibonacci.sol:

14:     // iterate i from 2 to n-1 and
15:     // set entry equal to sum of two previous entries
16:     for (uint i=2; i < n ; i++) {
                               ^^^

debug(development:0x539e8bde...)> !evm.next.state.storage
  evm.next.state.storage { '0000000000000000000000000000000000000000000000000000000000000000': '000000000000000000000000000000000000000000000000000000000000000a',
  evm.next.state.storage   '290decd9548b62a8d60345a988386fc84ba6bc95484008f6362f93160ef3e563': '0000000000000000000000000000000000000000000000010100ffff00010100' } +0ms
```

**Comment by gnidan** [comment]
Just deployed the fix for this on `darq-truffle@4.1.7-latest.3`, @bmmpxf could you try it out and verify?

Thanks!

**Comment by bmmpxf** [comment]
Just tried it. Some progress, but not much. Given an expected:

```[1, 1, 0, 255, 255, 0, 1, 1, 0, 255]```

The output I got was:

```
  fibseries: [ 1,
               1,
               0,
               255,
               255,
               1,
               1,
               0,
               255,
               255,
               0,
               2,
               0,
               255,
               255 ]
```

With `!evm.next.state.storage` reporting:

```
  evm.next.state.storage { '0000000000000000000000000000000000000000000000000000000000000000': '000000000000000000000000000000000000000000000000000000000000000f',
  evm.next.state.storage   '290decd9548b62a8d60345a988386fc84ba6bc95484008f6362f93160ef3e563': '0000000000000000000000000000000000ffff000200ffff000101ffff000101' } 
```

So still extra terms, and I have no idea where that `2` is coming from.

**Comment by gnidan** [comment]
Oh that's weird @bmmpxf 

The `2` is definitely there in storage:
```
0000000000000000000000000000000000ffff000200ffff000101ffff000101
                                        ^^
```

**Comment by bmmpxf** [comment]
I saw that too, but I couldn't figure out where in the calculations it was coming from. Maybe it had to do with the `0 - 255` in there...

**Comment by gnidan** [comment]
@bmmpxf can you paste the erroneous Fibonacci.sol source here so I can play around with it?

**Comment by bmmpxf** [comment]
Erroneous Fibonacci below! It's just the regular Fibonacci but with subtraction instead of addition.

```
pragma solidity ^0.4.22;

contract Fibonacci {

uint8[] fibseries;

  // n = how many in the series to return
  function generateFib(uint n) public {

    // set 1st and 2nd entries to 1
    fibseries.push(1);
    fibseries.push(1);

    // generate subsequent entries
    for (uint i=2; i < n ; i++) {
      fibseries.push(fibseries[i-1] - fibseries[i-2]);
    }

  }
  
}
```

**Comment by gnidan** [comment]
Weird @bmmpxf I can't seem to reproduce this. I suspect that is happening because of outdated contract state? I'd say try again with `migrate --reset`

**Comment by bmmpxf** [comment]
Problem located! It had to do with re-running the contract, with interacts with the already-stored array in unexpected ways.

But the original issue has been resolved. Just tested with 4.1.8. Thanks!
